name: nstpy37
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib=3.4.3
  - numpy=1.20.1
  - pip
  - pip:
      - ipykernel==6.16.2 
      - opencv-python==4.5.4.60
      - torch==1.10.0+cu113
      - torchvision==0.11.1+cu113
      - torchaudio==0.10.0+cu113
      - --find-links https://download.pytorch.org/whl/cu113/torch_stable.html
